### ISSUE TITLE
.github workflow should not be published as part of the distro tarball

### ISSUE THREAD

**Issue by atoomic** [FGasper/p5-Net-Curl-Promiser#3]
Noticed this recently while updating the Net-Curl-Promiser to version 0.17

```
.github/workflows/linux.yml
.github/workflows/macos.yml
```

probably need one ignore somewhere `.git*` in dist.ini?

**Comment by atoomic** [comment]
also note that `.travis.yaml` is also shipped (this is not new)

**Comment by FGasper** [comment]
Fixed via 5f0a292. Thank you!
